name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 8
          distribution: temurin
          server-id: opencollab-snapshot-repo
          server-username: ${{ vars.DEPLOY_USER }}
          server-password: ${{ secrets.DEPLOY_PASS }}
      - name: Deploy with Maven
        run: mvn deploy -P deploy
